#ifndef LWRPSHADRES_SHADERLIBRARY_INSTANCING
#define LWRPSHADRES_SHADERLIBRARY_INSTANCING

#include "CoreRP/ShaderLibrary/UnityInstancing.hlsl"

#define INSTAINCING_PROPS_BEGIN UNITY_INSTANCING_BUFFER_START(Props)
#define INSTAINCING_PROPS_END UNITY_INSTANCING_BUFFER_END(Props)
#define INSTAINCING_PROP(type, var) UNITY_DEFINE_INSTANCED_PROP(type, var)
#define INSTAINCING_REF(var) UNITY_ACCESS_INSTANCED_PROP(Props, var)

#endif